version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app12"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-110zgpefz6pu6"
s3_prefix = "sam-app12"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
